version: "3"
services:
  db:
    # replace username/repo:tag with your name and image details
    image: postgres:latest
    env_file: postgres_env.properties
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: 300M
#      restart_policy:
#        condition: on-failure
    ports:
      - "5432:5432"
    networks:
      - webnet1
  keypr:
    # replace username/repo:tag with your name and image details
    image: keyprx:latest
    build: .
    env_file: postgres_env.properties
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: 300M
#      restart_policy:
#        condition: on-failure
    ports:
      - "8087:8080"
    volumes:
      - "/Users/david/IdeaProjects:/home/david/IdeaProjects"
    depends_on:
      - db
    networks:
      - webnet1
networks:
  webnet1:
    internal: false
